'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('turnos', [
            {
                id: 1,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "9:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 2,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "9:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 3,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "10:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 4,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "11:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 5,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "12:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 6,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "12:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 7,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "1:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 8,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "10:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 9,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "11:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 10,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "1:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 11,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "2:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 12,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "2:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 13,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "3:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 14,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "3:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 15,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "4:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 16,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "4:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 17,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "5:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 18,
                doctor: "doctor1",
                fecha: "29 08 2020",
                hora: "5:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 19,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "9:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 20,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "9:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 21,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "10:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 22,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "10:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 23,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "11:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 24,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "11:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 25,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "12:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 26,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "12:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 27,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "1:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 28,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "1:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 29,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "2:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 30,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "2:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 31,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "3:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 32,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "3:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 33,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "4:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 34,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "4:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 35,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "5:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 36,
                doctor: "doctor1",
                fecha: "31 08 2020",
                hora: "5:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 37,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "9:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 38,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "9:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 39,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "10:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 40,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "10:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 41,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "11:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 42,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "11:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 43,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "12:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 44,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "12:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 45,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "1:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 46,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "1:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 47,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "2:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 48,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "2:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 49,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "3:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 50,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "3:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 51,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "4:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 52,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "4:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 53,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "5:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 54,
                doctor: "doctor1",
                fecha: "01 09 2020",
                hora: "5:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 55,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "9:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 56,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "9:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 57,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "10:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 58,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "10:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 59,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "11:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 60,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "11:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 61,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "12:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 62,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "12:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 63,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "1:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 64,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "1:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 65,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "2:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 66,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "2:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 67,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "3:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 68,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "3:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 69,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "4:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 70,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "4:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 71,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "5:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 72,
                doctor: "doctor1",
                fecha: "04 09 2020",
                hora: "5:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 73,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "9:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 74,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "9:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 75,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "10:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 76,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "10:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 77,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "11:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 78,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "11:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 79,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "12:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 80,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "12:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 81,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "1:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 82,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "1:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 83,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "2:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 84,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "2:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 85,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "3:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 86,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "3:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 87,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "4:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 88,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "4:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 89,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "5:00",
                duracion: 30,
                paciente: null,
            },
            {
                id: 90,
                doctor: "doctor1",
                fecha: "05 09 2020",
                hora: "5:30",
                duracion: 30,
                paciente: null,
            },
            {
                id: 91,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "9:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 92,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "9:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 93,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "10:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 94,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "9:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 95,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "10:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 96,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "10:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 97,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "11:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 98,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "11:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 99,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "11:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 100,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "12:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 101,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "12:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 102,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "12:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 103,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "1:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 104,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "1:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 105,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "1:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 106,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "2:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 107,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "2:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 108,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "2:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 109,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "3:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 110,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "3:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 111,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "3:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 112,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "4:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 113,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "4:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 114,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "4:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 115,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "5:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 116,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "5:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 117,
                doctor: "doctor2",
                fecha: "31 08 2020",
                hora: "5:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 118,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "9:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 119,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "9:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 120,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "9:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 121,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "10:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 122,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "10:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 123,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "10:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 124,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "11:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 125,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "11:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 126,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "11:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 127,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "12:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 128,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "12:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 129,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "12:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 130,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "1:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 131,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "1:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 132,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "1:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 133,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "2:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 134,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "2:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 135,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "2:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 136,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "3:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 137,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "3:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 138,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "3:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 139,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "4:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 140,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "4:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 141,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "4:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 142,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "5:00",
                duracion: 20,
                paciente: null,
            },
            {
                id: 143,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "5:20",
                duracion: 20,
                paciente: null,
            },
            {
                id: 144,
                doctor: "doctor2",
                fecha: "01 09 2020",
                hora: "5:40",
                duracion: 20,
                paciente: null,
            },
            {
                id: 145,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "9:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 146,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "9:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 147,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "10:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 148,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "12:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 149,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "11:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 150,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "1:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 151,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "11:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 152,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "1:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 153,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "2:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 154,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "3:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 155,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "3:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 156,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "4:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 157,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "5:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 158,
                doctor: "doctor3",
                fecha: "02 09 2020",
                hora: "5:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 159,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "9:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 160,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "9:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 161,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "10:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 162,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "11:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 163,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "11:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 164,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "12:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 165,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "2:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 166,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "1:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 167,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "1:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 168,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "3:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 169,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "3:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 170,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "4:20",
                duracion: 40,
                paciente: null,
            },
            {
                id: 171,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "5:00",
                duracion: 40,
                paciente: null,
            },
            {
                id: 172,
                doctor: "doctor3",
                fecha: "03 09 2020",
                hora: "5:40",
                duracion: 40,
                paciente: null,
            },
            {
                id: 173,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "9:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 174,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "9:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 175,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "9:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 176,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "9:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 177,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "9:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 178,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "9:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 179,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "10:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 180,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "10:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 181,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "10:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 182,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "10:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 183,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "10:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 184,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "10:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 185,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "11:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 186,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "11:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 187,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "11:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 188,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "11:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 189,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "11:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 190,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "11:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 191,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "12:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 192,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "12:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 193,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "12:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 194,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "12:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 195,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "12:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 196,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "12:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 197,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "1:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 198,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "1:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 199,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "1:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 200,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "1:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 201,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "1:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 202,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "1:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 203,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "2:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 204,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "2:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 205,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "2:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 206,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "2:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 207,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "2:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 208,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "2:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 209,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "3:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 210,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "3:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 211,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "3:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 212,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "3:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 213,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "3:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 214,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "3:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 215,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "4:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 216,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "4:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 217,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "4:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 218,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "4:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 219,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "4:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 220,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "4:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 221,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "5:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 222,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "5:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 223,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "5:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 224,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "5:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 225,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "5:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 226,
                doctor: "doctor3",
                fecha: "04 09 2020",
                hora: "5:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 227,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "9:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 228,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "9:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 229,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "9:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 230,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "9:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 231,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "10:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 232,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "10:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 233,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "9:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 234,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "9:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 235,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "10:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 236,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "10:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 237,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "10:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 238,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "10:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 239,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "11:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 240,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "11:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 241,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "11:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 242,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "11:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 243,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "11:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 244,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "11:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 245,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "12:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 246,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "12:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 247,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "12:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 248,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "12:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 249,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "12:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 250,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "12:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 251,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "1:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 252,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "1:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 253,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "1:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 254,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "1:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 255,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "1:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 256,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "1:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 257,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "2:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 258,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "2:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 259,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "2:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 260,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "2:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 261,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "2:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 262,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "2:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 263,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "3:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 264,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "3:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 265,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "3:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 266,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "3:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 267,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "3:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 268,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "3:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 269,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "4:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 270,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "4:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 271,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "4:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 272,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "4:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 273,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "4:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 274,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "4:50",
                duracion: 10,
                paciente: null,
            },
            {
                id: 275,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "5:00",
                duracion: 10,
                paciente: null,
            },
            {
                id: 276,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "5:10",
                duracion: 10,
                paciente: null,
            },
            {
                id: 277,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "5:20",
                duracion: 10,
                paciente: null,
            },
            {
                id: 278,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "5:30",
                duracion: 10,
                paciente: null,
            },
            {
                id: 279,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "5:40",
                duracion: 10,
                paciente: null,
            },
            {
                id: 280,
                doctor: "doctor4",
                fecha: "04 09 2020",
                hora: "5:50",
                duracion: 10,
                paciente: null,
            }])
    },

    down: async (queryInterface, Sequelize) => {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    }
};
